version: 0.0
os: linux

files:             
  - source: LMSApp-0.0.1-SNAPSHOT.war
    destination: /opt/tomcat/webapps
  - source: amazon-cloudwatch-agent.json
    destination: /opt/aws/amazon-cloudwatch-agent/etc/

hooks:
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: centos
  ApplicationStart:
    - location: ./applicationstart.sh
      timeout: 180
      runas: centos
