version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    # environment:
    #   # Customize the JVM maximum heap limit
    #   MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get -y -qq install awscli
            aws --version
      - run:
          name: Build JAR and Run Unit Tests
          command: |
            cd webapp/LMSApp
            mvn clean package
      - run:
          name: Zip JAR File
          command: |
            mkdir package
            mv infrastructure/aws/codedeploy/applicationstart.sh package/
            mv infrastructure/aws/codedeploy/afterInstall.sh package/
            mv webapp/LMSApp/target/LMSApp-0.0.1-SNAPSHOT.war package/
            mv appspec.yml package/
            mv infrastructure/aws/config/cloudwatchagent.json package/
            cd package
            zip application.zip LMSApp-0.0.1-SNAPSHOT.war applicationstart.sh afterInstall.sh appspec.yml cloudwatchagent.json
            chmod 777 application.zip 
      - run:
          name: Upload ZIP to S3 bucket
          command: aws s3 cp package/application.zip s3://code-deploy.csye6225-su19-$AWS_BUCKET_NAME.me
      - run:
          name: Create Deployment
          command: aws deploy create-deployment --application-name csye6225-webapp --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name csye6225-webapp-deployment --region=$AWS_REGION --s3-location bucket=code-deploy.csye6225-su19-$AWS_BUCKET_NAME.me,bundleType=zip,key=application.zip


